#
# FYI: This file is replaced by a copy for deploys
# to ci, pre_production, and production.
#
pg_settings: &pg_settings
  adapter:  postgresql
  encoding: unicode
  database: vecnet
  pool:     5
  timeout:  5000
  username: vecnet
  password: vecnet

development: &development
  adapter:  sqlite3
  database: db/development.sqlite3
  pool:     5
  timeout:  5000

development_remote_purl_database:
  <<: *development

test: &test
  <<: *development
  database: db/test.sqlite3

qa:
  <<: *pg_settings
  database: vecnet_qa

production:
  <<: *pg_settings
  database: vecnet_dlvecnet
