#
# FYI: This file is replaced by a copy for deploys
# to ci, pre_production, and production.
#
sqlite_settings: &sqlite_settings
  adapter: sqlite3
  pool:    5
  timeout: 5000

development: &development
  <<: *sqlite_settings
  database: db/development.sqlite3

development_remote_purl_database:
  <<: *development

test: &test
  <<: *development
  database: db/test.sqlite3

test_remote_purl_database:
  <<: *test

ci: &ci
  <<: *test

ci_remote_purl_database:
  <<: *ci